site_name: "Seqera Platform: Demonstration Walkthrough"

theme:
  name: material
  logo: assets/logo.svg
  features:
    - content.tooltips
    - navigation.footer
    - navigation.tabs
    - navigation.path
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
    - toc.integrate
    - content.tabs.link
    - content.code.copy
    - content.action.edit
    - content.action.view

  font:
    text: Sans Serif

  palette:
    primary: dark purple
    accent: dark purple

  icon:
    admonition:
      note: octicons/tag-16
      info: octicons/info-16
      advanced: octicons/squirrel-16

repo_url: https://github.com/ejseqera/showcase #TODO
copyright: Copyright &copy; 2024 Seqera

extra_css:
  - "style.css"

extra_javascript:
  - https://buttons.github.io/buttons.js

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - md_in_html
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - Showcase Demonstration:
      - Getting Started: 001_home_page.md
      - What is Nextflow?: 002_what_is_nextflow.md
      - What is the Seqera Platform?: 003_what_is_the_seqera_platform.md
      - Accessing the Platform: 004_accessing_the_platform.md
      - Launching pipelines: 005_launching_pipelines.md
      - Monitoring runs: 008_monitoring_runs.md
      - Viewing run information: 009_viewing_run_information.md
      - Optimizing pipelines: 010_optimizing_pipelines.md
      - Using Data Explorer: 011_using_data_explorer.md
      - Introduction to Data Studios: 012_introduction_to_data_studios.md
      - Automation on the Seqera Platform: 014_automation_on_the_seqera_platform.md
      - Walthrough summary: 015_walkthrough_summary.md
      - Resources: 016_resources.md
